Use different release of a recipe in local development.
By using a different release of "plone.recipe.zope2instance" we can get rid of the following error which occurs during `bin/buildout`:

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/mbaechtold/.buildout/eggs/cp27m/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/Users/mbaechtold/.buildout/eggs/cp27m/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/mbaechtold/.buildout/eggs/cp27m/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/Users/mbaechtold/.buildout/eggs/cp27m/plone.recipe.zope2instance-4.2.21-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 95, in install
    major, minor = parsed[0:2]
TypeError: 'Version' object has no attribute '__getitem__'